---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Lint/HandleExceptions:
  Exclude:
    - spec/**/*_spec.rb

Lint/RescueException:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 80
  Exclude:
    - spec/**/*_spec.rb

Style/AccessorMethodName:
  Exclude:
    - spec/**/*_spec.rb

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/FileName:
  Enabled: false

Style/Lambda:
  Exclude:
    - spec/**/*_spec.rb

Style/LambdaCall:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Semicolon:
  Exclude:
    - spec/**/*_spec.rb

Style/SignalException:
  EnforcedStyle: semantic

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - spec/**/*_spec.rb

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpecialGlobalVars:
  Exclude:
    - Gemfile
    - dry-initializer.gemspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Exclude:
    - spec/**/*_spec.rb
